name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Mamba install dependencies
      shell: bash -l {0}
      run: mamba install python=${{ matrix.python-version }} pip nodejs ipywidgets jupyter jupyterlab pillow numpy flake8

    - name: Install ipycanvas
      shell: bash -l {0}
      run: pip install -e .

    - name: Install labextension (Only on Ubuntu for build speed)
      if: matrix.os == 'ubuntu-latest'
      shell: bash -l {0}
      run: jupyter labextension install .

    - name: Test flake8
      shell: bash -l {0}
      run: flake8 ipycanvas --ignore=E501
