name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        auto-update-conda: true
        update-conda: true
        conda-channels: conda-forge

    - name: Conda install dependencies
      run: conda install python=${{ matrix.python-version }} pip nodejs ipywidgets jupyter jupyterlab pillow flake8

    - name: Install ipycanvas
      run: pip install -e .

    - name: Install labextension (Only on Ubuntu for build speed)
      if: matrix.os == 'ubuntu-latest'
      run: jupyter labextension install .

    - name: Test flake8
      run: flake8 ipycanvas --ignore=E501
